version: '3'
services:
  frontend:
    build: ./front
    restart: always
    ports:
      - "3000:3000"  # Le front-end écoute sur le port 3000 en interne et est exposé sur le port 8080 sur l'hôte
    networks:
      - mynetwork


  api:
    build: ./api
    restart: always
    ports:
      - "3001:3001"  # L'API est accessible via le port 3001 sur l'hôte
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/base_test
    depends_on:
      - postgres
    volumes:
    - ./api/__tests__:/usr/src/app
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: base_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Montage du fichier nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
