name: Perpare Deploy, Build, Run, Test et Finalize Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-env-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS (env_test)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ ! -d ~/env_test ]; then
              mkdir -p ~/env_test
              git clone https://github.com/${{ REPO }} ~/env_test
            fi
            cd ~/env_test
            git pull origin main

  build-env-test:
    runs-on: ubuntu-latest
    needs: deploy-to-env-test

    steps:
      - name: Build Docker Containers (env_test)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/env_test
            sudo docker-compose down 
            yes | sudo docker image prune -a
            sudo docker-compose build

  run-env-test:
    runs-on: ubuntu-latest
    needs: build-env-test

    steps:
      - name: Start Docker Containers (env_test)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/env_test
            sudo docker-compose up -d

  wait-for-api-env-test:
    runs-on: ubuntu-latest
    needs: run-env-test

    steps:
      - name: Wait for API to be ready (env_test)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            while ! curl -sSf http://localhost:3001/api/dogs > /dev/null; do
              echo "Waiting for API to be ready..."
              sleep 5
            done
            echo "API is ready!"

  test-env-test:
    runs-on: ubuntu-latest
    needs: wait-for-api-env-test

    steps:
      - name: Run Tests (env_test)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/env_test/api
            if ! command -v npm &> /dev/null; then
              echo "npm could not be found, installing..."
              curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            npm install
            npm run test

            if [ $? -ne 0 ]; then
              echo "Tests failed, exiting with error."
              exit 1
            fi

  finalize-deploy:
    runs-on: ubuntu-latest
    needs: test-env-test

    steps:
      - name: Deploy to VPS (thomas)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ ! -d ~/thomas ]; then
              mkdir -p ~/thomas
              git clone https://github.com/${{ github.REPO }} ~/thomas
            fi
            cd ~/thomas
            git pull origin main

      - name: Build Docker Containers (thomas)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/thomas
            sudo docker-compose down 
            yes | sudo docker image prune -a
            sudo docker-compose build

      - name: Start Docker Containers (thomas)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/thomas
            sudo docker-compose up -d
