- name: Deploy to VPS
  uses: appleboy/ssh-action@v0.1.8
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USERNAME }}
    password: ${{ secrets.VPS_PASSWORD }}
    port: ${{ secrets.VPS_PORT }}
    script: |
      cd ~/myapp || mkdir ~/myapp && cd ~/myapp
      git clone https://github.com/LegrandThomas/test_deploy.git . || git pull origin main
      docker-compose down
      docker-compose up -d --build
