name: Deploy, Build, Run, and Test

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy, Build, Run, and Test on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Change directory to the project folder or clone if it doesn't exist
            cd ~/thomas || (mkdir ~/thomas && cd ~/thomas && git clone https://github.com/${{ github.repository }} .)

            # Pull the latest changes
            git pull origin main

            # Build Docker containers
            sudo docker-compose down -v
            yes | sudo docker image prune -a
            sudo docker-compose build

            # Start Docker containers
            sudo docker-compose up -d

            # Wait for the API to be ready
            while ! curl -sSf http://localhost:3001/api/dogs > /dev/null; do
              echo "Waiting for API to be ready..."
              sleep 5
            done
            echo "API is ready!"

            # Run Tests
            cd ~/thomas/api
            if ! command -v npm &> /dev/null
            then
              echo "npm could not be found, installing..."
              curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            npm install
            npm run test

            # Check test results and finalize deployment if tests pass
            if [ $? -eq 0 ]; then
              echo "Tests passed, finalizing deployment..."
              sudo docker-compose up -d
            else
              echo "Tests failed, exiting with error."
              exit 1
            fi
