name: Deploy, Build, Run and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/thomas || mkdir ~/thomas && cd ~/thomas
            git pull origin main
            sudo docker-compose down -v
            sudo docker image prune -a
            sudo docker-compose up -d --build

  build:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Containers
        run: |
          docker-compose pull
          docker-compose build

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Containers
        run: docker-compose up -d

      - name: Wait for containers to start
        run: sleep 30s  # Adjust based on your application startup time

  test:
    runs-on: ubuntu-latest
    needs: run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies and Run Tests
        run: |
          docker exec thomas_api_1 npm install --prefix ./api
          docker exec thomas_api_1 npm run test
