name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Containers
        run: |
          docker-compose down -v
          docker-compose up -d --build

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Containers
        run: docker-compose up -d

  test:
    runs-on: ubuntu-latest
    needs: run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: docker-compose exec thomas_api_1 npm install

      - name: Run Tests
        run: docker-compose exec thomas_api_1 npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/thomas || mkdir ~/thomas && cd ~/thomas
            git pull origin main
            sudo docker-compose down -v
            sudo docker image prune -a
            sudo docker-compose up -d --build
