name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker-compose build

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker containers
        run: docker-compose up -d

  test:
    runs-on: ubuntu-latest
    needs: run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose exec api npm run test
      - name: Stop Docker containers
        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/thomas || mkdir ~/thomas && cd ~/thomas
            git pull origin main
            sudo docker-compose down -v
            sudo docker image prune -a
            sudo docker-compose up -d --build
